index = "nips00"
corpus = "line.toml"
dataset = "nips00"
prefix = "."
stop-words = "lemur-stopwords.txt"
[[analyzers]]
	ngram = 1
	method = "ngram-word"
	[[analyzers.filter]]
		type = "icu-tokenizer"
	[[analyzers.filter]]
		type = "lowercase"
